### ISSUE TITLE
Add pivot root

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root-pkg#2]
Hi,

Please, add `pivot_root` support

Thank you !

**Comment by ailispaw** [comment]
Here?
Done at https://github.com/ailispaw/docker-root/commit/17753385439b4e4fc79761b51ceaa346d87788ae

**Comment by ailispaw** [comment]
FYI: @cedvan 
Just released v1.3.2
https://github.com/ailispaw/docker-root/releases/tag/v1.3.2
- Add an ability to switch between Docker versions
- Add Package Installer
- Add docker-root.switch_root to kernel parameter by default to use pivot_root

**Comment by cedvan** [comment]
Great !
