### ISSUE TITLE
Install glusterfs

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root-pkg#3]
Hi,

Possible install glusterfs ?

Thank you !

**Comment by ailispaw** [comment]
What is a benefit of that?
Did you get a working container with mariadb & glusterfs finally?

**Comment by ailispaw** [comment]
I mean how the test with the custom box is going?

**Comment by ailispaw** [comment]
Can you make glusterfs working in a container as a volume container instead of in a host VM?

**Comment by ailispaw** [comment]
MEMO:
http://download.gluster.org/pub/gluster/glusterfs/3.7/
http://www.gluster.org/community/documentation/index.php/Building_GlusterFS#Building_from_Source

**Comment by cedvan** [comment]
Convoy glusterfs works now :smiley: ! 
I don't need this request :wink:

**Comment by ailispaw** [comment]
@cedvan Oh, great!
